# Generated by Django 5.2.10 on 2026-02-01 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='组合代码')),
                ('name', models.CharField(max_length=200, verbose_name='组合名称')),
                ('manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='投资经理')),
                ('portfolio_type', models.CharField(choices=[('stock', '股票组合'), ('bond', '债券组合'), ('mixed', '混合组合'), ('index', '指数组合'), ('qdii', 'QDII组合'), ('other', '其他')], default='mixed', max_length=20, verbose_name='组合类型')),
                ('status', models.CharField(choices=[('active', '运行中'), ('suspended', '暂停'), ('closed', '已关闭')], default='active', max_length=20, verbose_name='状态')),
                ('asset_scale', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='资产规模(元)')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '投资组合',
                'verbose_name_plural': '投资组合',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('threshold', '阈值预警'), ('anomaly', '异常预警'), ('limit', '限制预警'), ('trend', '趋势预警')], max_length=20, verbose_name='预警类型')),
                ('severity', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], default='warning', max_length=20, verbose_name='预警等级')),
                ('title', models.CharField(max_length=200, verbose_name='预警标题')),
                ('content', models.TextField(verbose_name='预警内容')),
                ('indicator_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='指标名称')),
                ('indicator_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='指标值')),
                ('threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='阈值')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('acknowledged', '已确认'), ('resolved', '已解决'), ('ignored', '已忽略')], default='pending', max_length=20, verbose_name='状态')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('handle_comment', models.TextField(blank=True, null=True, verbose_name='处理意见')),
                ('notified', models.BooleanField(default=False, verbose_name='是否已通知')),
                ('notification_time', models.DateTimeField(blank=True, null=True, verbose_name='通知时间')),
                ('alert_time', models.DateTimeField(auto_now_add=True, verbose_name='预警时间')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='risk.portfolio', verbose_name='组合')),
            ],
            options={
                'verbose_name': '风险预警',
                'verbose_name_plural': '风险预警',
                'ordering': ['-alert_time'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('buy', '买入'), ('sell', '卖出')], max_length=10, verbose_name='交易类型')),
                ('security_type', models.CharField(choices=[('stock', '股票'), ('bond', '债券'), ('fund', '基金'), ('derivative', '衍生品'), ('other', '其他')], max_length=20, verbose_name='证券类型')),
                ('security_code', models.CharField(max_length=20, verbose_name='证券代码')),
                ('security_name', models.CharField(max_length=200, verbose_name='证券名称')),
                ('trade_date', models.DateField(verbose_name='交易日期')),
                ('trade_time', models.TimeField(blank=True, null=True, verbose_name='交易时间')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='成交价格')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='成交金额')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='佣金')),
                ('stamp_tax', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='印花税')),
                ('transfer_fee', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='过户费')),
                ('status', models.CharField(choices=[('pending', '待成交'), ('partial', '部分成交'), ('filled', '全部成交'), ('cancelled', '已取消'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='是否异常')),
                ('abnormal_reason', models.TextField(blank=True, null=True, verbose_name='异常原因')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='risk.portfolio', verbose_name='组合')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'ordering': ['-trade_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holding_date', models.DateField(verbose_name='持仓日期')),
                ('security_type', models.CharField(choices=[('stock', '股票'), ('bond', '债券'), ('fund', '基金'), ('derivative', '衍生品'), ('other', '其他')], max_length=20, verbose_name='证券类型')),
                ('security_code', models.CharField(max_length=20, verbose_name='证券代码')),
                ('security_name', models.CharField(max_length=200, verbose_name='证券名称')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='持仓数量')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='持仓成本')),
                ('cost_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='持仓成本价')),
                ('market_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='市价')),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='市值')),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='浮动盈亏')),
                ('unrealized_pnl_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='浮动盈亏比例')),
                ('holding_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='持仓比例')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='risk.portfolio', verbose_name='组合')),
            ],
            options={
                'verbose_name': '持仓信息',
                'verbose_name_plural': '持仓信息',
                'ordering': ['-holding_date', '-market_value'],
                'unique_together': {('portfolio', 'holding_date', 'security_code')},
            },
        ),
        migrations.CreateModel(
            name='RiskIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_date', models.DateField(verbose_name='指标日期')),
                ('daily_return', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='日收益率')),
                ('cumulative_return', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='累计收益率')),
                ('annualized_return', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='年化收益率')),
                ('daily_volatility', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='日波动率')),
                ('annualized_volatility', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='年化波动率')),
                ('max_drawdown', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='最大回撤')),
                ('value_at_risk', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='VaR(95%)')),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='夏普比率')),
                ('sortino_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='索提诺比率')),
                ('information_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='信息比率')),
                ('industry_concentration', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='行业集中度')),
                ('stock_concentration', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='个股集中度')),
                ('top10_holdings_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='前十大持仓占比')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_indicators', to='risk.portfolio', verbose_name='组合')),
            ],
            options={
                'verbose_name': '风险指标',
                'verbose_name_plural': '风险指标',
                'ordering': ['-indicator_date', '-created_at'],
                'unique_together': {('portfolio', 'indicator_date')},
            },
        ),
    ]
